Implemented suggestion done in issue #1
VRMonkey/ue4-style-guide pull request #20
Opened 2024-02-21 18:26 UTC by lucastakejame

Só implementei o que eu tinha proposto na descrição do issue.

2024-03-06 17:23 UTC, beogivaljr requested changes

2024-03-06 17:23 UTC, beogivaljr commented on README.md
> +    |-- PacoteExternoQueAindaNãoFoiIntegradoCompletamente/
Acho que seria melhor escrever tudo em ingles pra ficar consistente com o resto.

2024-03-06 17:23 UTC, beogivaljr commented on README.md
> +    |   |-- Gameplay/ (Coisas relevantes pro jogo e dependencias como Arte/sons/Efeitos/Blueprints)
Eu não criaria a pasta "Gameplay". Acho que da pra jogar tudo que ta nela pra fora dela mesmo. Se não ficariam só duas pastas na raiz. E acho que acaba parecendo um pouco a velha divisão "Arte" vs "Gameplay".

2024-03-06 17:23 UTC, beogivaljr commented on README.md
> +    |   |   |   |   |   |-- A_SchoolBoy_Idle
Separar nomes por "_" acho que só se forem variações. Pelo menos no Honey a gente só separa por "_" quando é uma variação ou quando são siglas. Eu vou colocar aqui um texto que mandei no canal, veja se faz sentido e se vc concorda. talves até valha a pena passar esse texto pra cá.
Aqui vou deixar um comentário extra sobre a regra da Variant porque é uma regra que a princípio parece complicada mesmo.

A gente só separa usando "_" quando são prefixos, sufixos ou siglas (PollenShooter -> PS).
A única excessão a essa regra é quando temos as variantes (Variants), nesse caso separamos palavras não abreviadas. Por exemplo, ArrowHit_Normal, ArrowHit_Ping, FallMode_Gliding, FallMode_Diving etc.
Na dúvida façam o seguinte teste: 
"Normal" é um tipo de ou uma variante de "ArrowHit"? Sim!
"Diving" é um tipo de ou uma variante de "FallMode"? Sim!
"Shot" é um tipo de ou uma variante de "PollenShooter"? Não, então deveria ser A_PollenShooterShot ou A_PS_Shot

2024-03-15 17:22 UTC, beogivaljr commented on README.md
> +|   |-- Developers/ (Pasta usada para coisas que não estão prontas o suficiente pra estar no projeto)
Não é melhor traduzir esses comentários pro ingles também? 😬

2024-03-15 17:51 UTC, beogivaljr approved these changes

2024-03-18 20:46 UTC, ericacope approved these changes

2024-03-22 14:06 UTC, merged